version: "3.7"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    command: [sh, -c, "go build -mod vendor main.go && ./main"]
    environment:
      GO111MODULE: 'on'
    links:
      - db
  db:
    image: mysql:5.7
    expose:
      - "3306"
#    ports:
#      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"
#      MYSQL_USER: "test"
#      MYSQL_PASSWORD: "test"
volumes:
  db_data: